qld-gov-au/ckanext-data-qld-theme

- ckanext/data_qld_theme/templates/group/index.html
- ckanext/data_qld_theme/templates/group/snippets/helper.html
- ckanext/data_qld_theme/templates/organization/index.html
- ckanext/data_qld_theme/templates/organization/snippets/helper.html
"What are organisations?" and "What are groups?"
> Changed the description text of 

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/templates/datarequests/show.html
- ckanext/data_qld_theme/templates/schema/show.html
- ckanext/data_qld_theme/templates/scheming/display_snippets/schema_link.html
Hiding the JSON button for Resource Data Schema
> Implementing changes to open resource data schema

- ckanext/data_qld_theme/templates/datarequests/base.html
- ckanext/data_qld_theme/templates/datarequests/index.html
Updated Data Requests left hand side bar text as per the supplied spreadsheet.
> [DQL-50] Update Data Requests LHS wording as per spreadsheet.

- ckanext/data_qld_theme/templates/home/index.html
Fixed twitter.
I worked on windows today hence many greenlines. nothing changed except twitter card.
> Training home

- ckanext/data_qld_theme/templates/home/index.html
Somehow this commit was left out of the previous pull request.
> Fix Twitter

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/templates/user/snippets/login_form.html
This PR also cleans up the Save button on the comment form.
> [DQL-100] Disable autocomplete on login form.

- ckanext/data_qld_theme/fanstatic/resource_file_upload.js
- ckanext/data_qld_theme/templates/snippets/organization.html
Organisations without a description do not show anything under the organisation name on the left hand side bar
> Added required asterisk for resource file/url upload fields

- ckanext/data_qld_theme/templates/home/index.html
- Update tiles to match https://www.qld.gov.au/data/home
- Move the 'container' div inside the 'content' div so we get the white background.
> Qol 5448 fix homepage

- ckanext/data_qld_theme/templates/home/index.html
Add new tile and remove the oldest.
> Dc 11614 add govhack 2019

- ckanext/data_qld_theme/templates/package/comment_list.html
This PR swaps the order of the Save and Cancel/Clear buttons.
> [DQL-113] Swap order of Save and Cancel buttons.

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/templates/group/snippets/group_item.html
- ckanext/data_qld_theme/templates/group/snippets/group_list.html
[DQL-133] - Table columns not wrapping text for organisations and groups on mobile devices
[DQL-129] - Dataset navigation tabs displaying outside parent container on mobile devices
[DQL-131] - The remove button in the groups table for a dataset is being truncated on mobile devices
> Browser compatibility issues

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/plugin.py
- ckanext/data_qld_theme/templates/package/comment_list.html
This PR contains the following Jira stories:
- DQL-143: CKAN - Update frequency drop-down list remediation
- DQL-131: Browser Compatibility issue - The remove button in the groups tab is not displayed correctly
- DQL-129: Browser compatibility issues - When clicked on the Dataset related items the highlighted tab is out of line in Mobile devices
- DQL-85: BE - Resource Metadata - File Type Selector
- DQL-133: Browser compatibility issues - Tables are not formatted properly to display the organisations ,groups
- DQL-45: Variation - Comments - Implement "Mute & Follow Data Set (nice-to-have have ACs)
> Training to develop

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/templates/package/snippets/resource_item.html
Testing increased truncate value for labels (Dataset page, left hand dataset navbar) and also floating the dataset badge to the right.
> QOL-5856 Increased templates truncate value and float styles

- .gitignore
- ckanext/data_qld_theme/plugin.py
- ckanext/data_qld_theme/templates/robots.txt
- requirements-dev.txt
based on background changing and moving robots.txt to template folder
> Dynamic robots.txt

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/fanstatic/main.css
- ckanext/data_qld_theme/templates/datarequests/snippets/datarequest_item.html
- ckanext/data_qld_theme/templates/package/snippets/resource_item.html
- ckanext/data_qld_theme/templates/package/snippets/resources.html
- ckanext/data_qld_theme/templates/page.html
> QOL 5856 truncate

- .docker/Dockerfile.ckan
- .docker/scripts/create-test-data.sh
- README.md
- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/fanstatic/main.css
- ckanext/data_qld_theme/plugin.py
- ckanext/data_qld_theme/templates/base.html
- ckanext/data_qld_theme/templates/datarequests/snippets/datarequest_item.html
- ckanext/data_qld_theme/templates/package/snippets/resource_item.html
- ckanext/data_qld_theme/templates/package/snippets/resources.html
- ckanext/data_qld_theme/templates/page.html
- docker-compose.yml
DC-13148 - data.qld.gov.au header inconsistency between CKAN and Matrix
QOL-5847 - Open Data - IE and Edge Text wrapping in left column
QOL-5852 - Open Data - Hide highlighting popular datasets and resources (flame icon)
QOL-5853 - Open data - Change resource listing titles and breadcrumbs trail to display in full
QOL-5856 - Dataset Listing Page - increase truncation limit
> CHG-5762/QOL 5856 truncate tasks

- ckanext/data_qld_theme/fanstatic/data_qld.css
- ckanext/data_qld_theme/fanstatic/main.css
Removed popular icon overide from main to qld theme files, changed to visibility for accessibility
> QOL-5852 Removed popular icon overide 

- ckanext/data_qld_theme/fanstatic/data_qld.css
Update to MS word-break attribute and override on break-word
> QOL-5853 Update to MS word-break and override

- ckanext/data_qld_theme/fanstatic/data_qld.css
Updated clearfix attribute for aside before selector, running test in dev as my local vagrant is no longer running.
> DC-13484 Changed z-index on clearfix before

- ckanext/data_qld_theme/fanstatic/data_qld.css
Reverting clearfix. changed to wrapper:before - running test in dev env.
> Dc 13484 Android issue

- ckanext/data_qld_theme/fanstatic/data_qld.css
> Update to data.qld.gov aside issue (Android)

- ckanext/data_qld_theme/plugin.py
Use CKAN common request object for better error handling.
> Qol 6343 dashboard error

- requirements-dev.txt
- test/features/environment.py
Fix `/dashboard` and `/user/edit` to give correct error pages when not logged in. Compare https://dev.data.qld.gov.au/dashboard with https://staging.data.qld.gov.au/dashboard
> Develop to master

- ckanext/data_qld_theme/templates/base.html
- don't look for specific controller names, just check whether the necessary organisation data is present
> [DQL-183] adjust base template to handle custom controller

- ckanext/data_qld_theme/templates/base.html
- ckanext/data_qld_theme/templates/datarequests/show.html
- ckanext/data_qld_theme/templates/datarequests/snippets/datarequest_item.html
- ckanext/data_qld_theme/templates/package/comment_list.html
- ckanext/data_qld_theme/templates/scheming/package/read.html
- requirements-dev.txt
- requirements.txt
Reverts qld-gov-au/ckanext-data-qld-theme#149
> Revert "Develop to master"

- .docker/test.ini
- ckanext/data_qld_theme/templates/datarequests/base.html
- ckanext/data_qld_theme/templates/datarequests/close.html
- ckanext/data_qld_theme/templates/datarequests/edit.html
- ckanext/data_qld_theme/templates/datarequests/index.html
- ckanext/data_qld_theme/templates/datarequests/show.html
- ckanext/data_qld_theme/templates/datarequests/snippets/datarequest_item.html
- This is necessary for the replacement of Pylons with Flask.
> [QOL-7970] update datarequest links to use named routes

- .ahoy.yml
- .circleci/process-artifacts.sh
- .circleci/test.sh
- .docker/Dockerfile.ckan
- .docker/scripts/ckan_cli
- .docker/scripts/create-test-data.sh
- .docker/scripts/init-ext.sh
- .docker/scripts/init.sh
- .docker/scripts/serve.sh
- .docker/test.ini
- .env
- .github/workflows/test.yml
- ckanext/data_qld_theme/templates/robots.txt
- docker-compose.yml
- requirements-dev.txt
- setup.py
- test/features/environment.py
- test/features/login.feature
- test/features/navigation.feature
- Move S3 robots block into prod area since non-prod already disallows all
- Sync CI config with other repos
> QOL-8104 Cleanup

- ckanext/data_qld_theme/templates/header.html
Added three logo images. Different Images will be shown depend on browser width.
> using different logo images based on the screen size

- ckanext/data_qld_theme/templates/package/resource_read.html
- ckanext/data_qld_theme/templates/package/snippets/resource_form.html
- there doesn't seem to be an option that is compatible with both, so include both implementations with a version check
> [QOL-7811] handle both Pylons and Flask routing for resource edits

- ckanext/data_qld_theme/templates/package/resource_read.html
- ckanext/data_qld_theme/templates/package/snippets/resource_form.html
Jinja gives an error if a block is defined twice.
> [QOL-7811] pull common HTML elements outside conditional block

- ckanext/data_qld_theme/templates/package/snippets/package_form.html
- test/features/steps/steps.py
retain Pylons routing for CKAN < 2.9
> QOL-7811 fix bug in CKAN 2.9 routing

- .ahoy.yml
- .docker/Dockerfile.ckan
- .docker/scripts/create-test-data.sh
- .docker/scripts/serve.sh
- .docker/test.ini
- .github/workflows/test.yml
- ckanext/data_qld_theme/templates/package/group_list.html
- ckanext/data_qld_theme/templates/package/resource_read.html
- ckanext/data_qld_theme/templates/package/snippets/resource_form.html
- requirements-dev.txt
- test/features/admin_reporting.feature
- test/features/comments.feature
- test/features/config.feature
- test/features/data_request.feature
- test/features/data_usability_rating.feature
- test/features/data_validation.feature
- test/features/dataset_deletion.feature
- test/features/de_identified_data.feature
- test/features/engagement_reporting.feature
- test/features/environment.py
- test/features/google_analytics.feature
- test/features/login_redirect.feature
- test/features/resource_availability.feature
- test/features/resource_freshness.feature
- test/features/schema_metadata.feature
- test/features/user_creation.feature
- test/fixtures/html_resource.html
- test/fixtures/test-resource_schemea.json
- The theme interacts with many other extensions, so it should run the tests for each of them.
> QOL-7811 copy more tests from infrastructure project

- .ahoy.yml
- .docker/Dockerfile.ckan
- .docker/scripts/ckan_cli
- .docker/scripts/create-test-data.sh
- .docker/scripts/init.sh
- .docker/scripts/serve.sh
- .docker/test.ini
- .flake8
- .github/workflows/test.yml
- .gitignore
- ckanext/data_qld_theme/templates/base.html
- ckanext/data_qld_theme/templates/package/read.html
- ckanext/data_qld_theme/templates/package/resource_read.html
- docker-compose.yml
- requirements-dev.txt
- test/features/config.feature
- test/features/dataset_deletion.feature
- test/features/login_redirect.feature
- test/features/steps/steps.py
- test/features/user_creation.feature
- Drop kludge based on detecting ckanext-data-qld controller, instead copy the block into specific templates as required.
> QOL-8595 fix DC metadata in page source

- .circleci/build.sh
- setup.py
- test/features/resource_availability.feature
> [QOL-8595] drop cleanup scenario that may be causing a race condition
